<?php

namespace AboutYou\Cloud\AdminApi\Models;

/**
 * @property string $assetUrl URL of the image, generated by SCAYLE.
 */
class AssetUrl extends ApiObject
{
    protected $defaultValues = [
    ];

    protected $classMap = [
    ];

    protected $collectionClassMap = [
    ];

    protected $polymorphic = [
    ];

    protected $polymorphicCollections = [
    ];
}
