<?php

namespace AboutYou\Cloud\AdminApi\Models;

/**
 * @property int $id The id of the brand created by Backbone Core.
 * @property string $name Name of the brand.
 * @property string $logoUrl Url of the image, either manually specified or generated by BACKBONE Core, if the AY Cloud CDN is used.
 * @property Attribute[] $attributes A list of attributes attached to the brand.
 */
class Brand extends ApiObject
{
    protected $defaultValues = [
    ];

    protected $classMap = [
    ];

    protected $collectionClassMap = [
        'attributes' => \AboutYou\Cloud\AdminApi\Models\Attribute::class,
    ];

    protected $polymorphic = [
    ];

    protected $polymorphicCollections = [
    ];
}
