<?php

declare(strict_types=1);

/*
 * This file is part of the AdminAPI PHP SDK provided by SCAYLE GmbH.
 *
 * (c) SCAYLE GmbH <https://www.scayle.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Scayle\Cloud\AdminApi\Models;

/**
 * @property int $id The ID of the brand created by SCAYLE.
 * @property string $name Name of the brand.
 * @property string $group Group name allowing to group different brands.
 * @property string $logoUrl URL of the image, either manually specified or generated by SCAYLE, if the SCAYLE CDN is used.
 * @property AssetSource $logoSource A source specifying where to download the logo from.
 * @property Attribute[] $attributes A list of attributes attached to the brand.
 * @property mixed $customData Arbitrary fields assigned to Brands
 */
class Brand extends ApiObject
{
    /** @var array<string, bool|string> */
    protected array $defaultValues = [
    ];

    /** @var array<string, string> */
    protected array $classMap = [
        'logoSource' => AssetSource::class,
    ];

    /** @var array<string, string> */
    protected array $collectionClassMap = [
        'attributes' => Attribute::class,
    ];

    /**
     * @var array<string, array{discriminator: string, mapping: array<string, string>}>
     */
    protected array $polymorphic = [
    ];

    /**
     * @var array<string, array{discriminator: string, mapping: array<string, string>}>
     */
    protected array $polymorphicCollections = [
    ];
}
