<?php

declare(strict_types=1);

/*
 * This file is part of the AdminAPI PHP SDK provided by SCAYLE GmbH.
 *
 * (c) SCAYLE GmbH <https://www.scayle.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Scayle\Cloud\AdminApi\Models;

/**
 * @property int $id ID assigned by SCAYLE.
 * @property string $referenceKey A key that uniquely identifies the asset within the tenant's ecosystem.
 * @property string $name User defined name of the image.
 * @property string $mimeType MIME type identified by SCAYLE.
 * @property int $position Specifies the position of the image. Counting starts with 0, so when a product image should be on the first position, you have to send 0.
 * @property AssetSource $source A source from where to upload an image.
 * @property string $assetUrl URL of the image, either manually specified or generated by SCAYLE, if the SCAYLE CDN is used.
 * @property Attribute[] $attributes A list of attributes attached to the image.
 */
class ProductImage extends ApiObject
{
    /** @var array<string, bool|string> */
    protected array $defaultValues = [
    ];

    /** @var array<string, string> */
    protected array $classMap = [
        'source' => AssetSource::class,
    ];

    /** @var array<string, string> */
    protected array $collectionClassMap = [
        'attributes' => Attribute::class,
    ];

    /**
     * @var array<string, array{discriminator: string, mapping: array<string, string>}>
     */
    protected array $polymorphic = [
    ];

    /**
     * @var array<string, array{discriminator: string, mapping: array<string, string>}>
     */
    protected array $polymorphicCollections = [
    ];
}
