<?php

namespace AboutYou\Cloud\AdminApi\Models;

/**
 * @property int $id ID assigned by SCAYLE.
 * @property string $referenceKey A key that uniquely identifies the asset within the tenant's ecosystem.
 * @property string $name User defined name of the image.
 * @property string $mimeType MIME type identified by SCAYLE.
 * @property int $position Specifies the position of the image.
 * @property AssetSource $source A source from where to upload an image.
 * @property string $assetUrl URL of the image, either manually specified or generated by SCAYLE, if the SCAYLE CDN is used.
 * @property Attribute[] $attributes A list of attributes attached to the image.
 */
class ProductImage extends ApiObject
{
    protected $defaultValues = [
    ];

    protected $classMap = [
        'source' => AssetSource::class,
    ];

    protected $collectionClassMap = [
        'attributes' => Attribute::class,
    ];

    protected $polymorphic = [
    ];

    protected $polymorphicCollections = [
    ];
}
